name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  run:

    runs-on: windows-latest
    name: Upload Code Coverage Report

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SetUp MySQL
        uses: ankane/setup-mysql@v1
        with: 
          mysql-version: 8.0
          database: test_ormppdb

      - name: Verify MySQL Connections
        run:  mysql -uroot -e'show databases;'

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: amd64

      - name: CMake configure & build
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build ${{github.workspace}}/build --config Release

      - name: Setup OpenCppCoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        working-directory: ${{github.workspace}}/build
        run: OpenCppCoverage.exe --sources ${{github.workspace}} --export_type cobertura:ormppCov.xml --cover_children -- ctest -C Release

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ runner.os }}
          name:  ${{ runner.os }}-coverage
          files: ${{github.workspace}}/ormppCov.xml

      - name: Upload Binary installer to release
        if: contains(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/_CPack_Packages/win64/IFW/*.exe
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true