name: macOS Monterey 12

on: [ push ]

jobs:
  build_on_mac:
    runs-on: macOS-12

    strategy:
      matrix:
        mode: [ Debug, Release ]
        ssl: [ ON, OFF ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: SetUp HomeBrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: SetUp MySQL
        uses: ankane/setup-mysql@v1
        with: 
          mysql-version: 8.0
          database: test_ormppdb
        
      - name: Verify MySQL Connections
        run: mysql -uroot -e'show databases;'

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
